name: deploy
on: [push, workflow_call]
jobs:
  deploy-ui-libraries:
    runs-on: self-hosted
    steps:
      - name: Checkout from ui-libraries
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Setup Node 20.10.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Clone from gitlab
        uses: netease-lcap/tyler@v1.0.0

      - name: Deploy to bucket
        run: node ./jimmy/app/pipelines/github/deploy-ui-libraries.js

      - name: Alert from Github
        if: ${{ failure() }}
        run: node ./jimmy/app/pipelines/github/alert-github.js